name: Github Page Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: echo Hello, world!

      - name: Move index html to pubulic folder
        run: |
          mkdir public
          mv index.html public

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "kenechukwuJosiah"
          git config user.email "kennysuccesskay@gmail.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force https://$GH_PAT@github.com/kenechukwuJosiah/Github-Page-Deployment-Demo.git gh-pages
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
